sudo: required
dist: trusty
language: node_js

node_js:
  - 6
 
before_script:
  - nvm install 6
  - npm install
  - npm install -g sequelize-cli
  - sudo -u postgres createuser andeladeveloper
  - createdb dms-test

script:
  - npm run test